### ISSUE TITLE
INSTALL_COMAND probably won't work

### ISSUE THREAD

**Issue by Mitranim** [fyne-io/bootstrap#2]
https://github.com/fyne-io/bootstrap/blob/546a0cc8a64862b4d5ef69953e172901336c4756/bootstrap.sh#L18

**Comment by ajwillia-ms** [comment]
Can you provide more information? What about this will not work?

**Comment by Mitranim** [comment]
```diff
-INSTALL_COMAND
+INSTALL_COMMAND
```

**Comment by ajwillia-ms** [comment]
Oh goodness, thank you for that - apologies for not seeing what you meant!
