### ISSUE TITLE
Provide updated EFL for Windows

### ISSUE THREAD

**Issue by zet4** [fyne-io/bootstrap#6]
Currently Win-build is serving heavily out-of-date libraries and as a result some functionality of fyne is broken/lacking on Windows.

Originally discussed at fyne-io/fyne#24

**Comment by zet4** [comment]
So far it seems everyone either uses ancient 1.11 from win-builds (which hasn't been updated in over 4 years!) or cross-compile it from linux to windows: https://phab.enlightenment.org/w/windows/

Kinda sucks 🙅‍♂️

**Comment by zet4** [comment]
@ajwillia-ms How about setting up TravisCI that will cross-compile the latest EFL and then bootstrap for windows would fetch the release (could have travis upload it to github or just use it directly I think)

**Comment by ajwillia-ms** [comment]
That's a great idea - to roll out binaries to support Fyne. I would like to do that for all platforms so that we can have a slim library to fall back to if the full version is not installed on the system.

I will see what we can do regarding a windows build (not sure how great EFL or travis support is for some of the complexities it will encounter)...

**Comment by zet4** [comment]
If I get a chance sometime this week I will around with this, I've got some experience with TravisCI already.
Regarding Linux and MacOSX I think I saw a travis-ci config in the official EFL repo.
And I think Windows build should be relatively easy, after all they have a guide for it on Phabricator.

**Comment by ajwillia-ms** [comment]
Cool, let me know how you get on!

**Comment by zet4** [comment]
@ajwillia-ms hey sorry I actually got distracted with another job and I am bad at multitasking, but I experiment with ci yesterday, I actually got it to build an EFL1.21.99[dev] (from master branch basically) but it seems to have weird rendering issues, probably API incompatibility 
![image](https://user-images.githubusercontent.com/1717852/47842142-8933c500-ddc4-11e8-975f-2458a3de119b.png)

I am going to try building a more stable release like 1.19 or 1.20 now, also these builds take about an hour so yay.

**Comment by ajwillia-ms** [comment]
Thanks for the update - sorry to hear that 1.21.99 is causing issues with Fyne. I will try to replicate here and investigate the problem.

**Comment by zet4** [comment]
So I got 1.19 built now as well, but I am having issue with fyne, for some reason it fails to redraw the view, only the first frame on the main window gets rendered, all events get handled properly (ie. buttons do open windows), but the resulting windows are empty/white, if I resize the main window it doesn't fill in the white space either. I am not sure if it's something wrong with the EFL build. I did play around with elementary_test.exe EFL ships with and that one doesn't have any issues regarding rendering.
![image](https://user-images.githubusercontent.com/1717852/47850849-606cf900-dddf-11e8-9907-ae731fedc0db.png)

For now you can find efl-1.19 here: https://github.com/zet4/efl-build/releases/tag/efl-1.19
Keep in mind this build still assumes win-builds layout and I just copy it over existing msys2/opt/windows_64 (overwriting any files), also it seems to put efl pkg-config into /lib rather than /lib64 so I had to modify the env to point to both folders (efl wants libpng-14.pc which is in /lib64)
I am sure there's a cleaner and better way to do this but for now testing it works I guess? Unless this is whats causing the issue but I am not sure how else to do it atm.

**Comment by ajwillia-ms** [comment]
I installed your 1.19 build and see the same issue. I have eliminated the run loop and the thread from the equation. It seems like the changes are not being sent for rendering but I’m not sure why. The E test apps do work so it could be something that the default E run loop does on windows that the Fyne loop does not. I will have to investigate further.

**Comment by andydotxyz** [comment]
The default Fyne driver no longer uses EFL - updating your fyne and examples checkout should resolve this issue.
